
//
//  URLChecker.swift
//  FreetimeTests
//
//  Created by B_Litwin on 10/11/18.
//  Copyright © 2018 Ryan Nystrom. All rights reserved.
//

import XCTest
@testable import Freetime

class URLChecker: XCTestCase {
    
    var url: String!
    var expected: RouteFromURL!
    
    var result: RouteFromURL? {
        return routeInAppFromGitHubURL(url: url)
    }
    
    func test_urlParts_PositiveMatches_ForIssues() {
        
        url = "https://github.com/GitHawkApp/GitHawk/issues/2274"
        expected = RouteFromURL.issue(
            owner: "GitHawkApp",
            repo: "GitHawk",
            number: 2274
        )
        
        XCTAssertEqual(result, expected)
        
    }
    
    func test_urlParts_PositiveMatches_ForRepositories() {
        
        url = "https://github.com/GitHawkApp/GitHawk"
        expected = RouteFromURL.repository(
            owner: "GitHawkApp",
            repository: "GitHawk"
        )
        
        XCTAssertEqual(result, expected)
        
        //adding a "/" to the end
        url = "https://github.com/GitHawkApp/GitHawk/"
        expected = RouteFromURL.repository(
            owner: "GitHawkApp",
            repository: "GitHawk"
        )
        
        XCTAssertEqual(result, expected)
        
    }
    
    func test_urlParts_NegativeMatches() {
        
        url = "https://github.com"
        XCTAssertNil(result)
        
        url = "https://github.com/githawkapp"
        XCTAssertNil(result)
        
        //adding a '/' at the end
        url = "https://github.com/githawkapp/"
        XCTAssertNil(result)
        
        url = "https://developer.github.com/v4/"
        XCTAssertNil(result)
        
    }
    
}

extension RouteFromURL: Equatable {
    
    public static func == (lhs: RouteFromURL, rhs: RouteFromURL) -> Bool {
        switch lhs {
        case .issue(let owner, let repo, let number):
            guard case let .issue(rhsOwner, rhsRepo, rhsNumber) = rhs else {
                return false
            }
            
            return owner == rhsOwner
                && repo == rhsRepo
                && number == rhsNumber
            
        case .repository(let owner, let repo):
            guard case let .repository(rhsOwner, rhsRepo) = rhs else {
                return false
            }
            
            return owner == rhsOwner
                && repo == rhsRepo
        }
    }
}



var links = [
    https://github.com/ajenti/ajenti
    http://djangosuit.com/
    https://github.com/sshwsfc/xadmin
    https://github.com/flask-admin/flask-admin
    https://github.com/mher/flower
    http://grappelliproject.com
    https://github.com/wooey/wooey
    https://github.com/keon/algorithms
    https://github.com/tylerlaberge/PyPattyrn
    https://github.com/faif/python-patterns
    http://www.grantjenks.com/docs/sortedcontainers/
    https://github.com/mbi/django-simple-captcha
    https://github.com/moqada/django-simple-spam-blocker
    https://github.com/django-compressor/django-compressor
    https://github.com/jazzband/django-pipeline
    https://github.com/jschneier/django-storages
    http://www.fanstatic.org/en/latest/
    http://wimleers.com/fileconveyor
    https://github.com/miracle2k/flask-assets
    https://github.com/jaysonsantos/jinja-assets-compressor
    https://github.com/miracle2k/webassets
    https://github.com/danilobellini/audiolazy
    https://github.com/beetbox/audioread
    http://beets.io/
    https://musicbrainz.org/
    https://github.com/worldveil/dejavu
    https://github.com/StreetVoice/django-elastic-transcoder
    https://aws.amazon.com/elastictranscoder/
    http://eyed3.nicfit.net/
    https://nedbatchelder.com/code/modules/id3reader.py
    https://github.com/globocom/m3u8
    http://bspaans.github.io/python-mingus/
    https://github.com/quodlibet/mutagen
    https://github.com/tyiannak/pyAudioAnalysis
    https://github.com/jiaaro/pydub
    https://github.com/echonest/pyechonest
    http://static.echonest.com/enspex/
    http://scikits.appspot.com/talkbox
    https://github.com/Parisson/TimeSide
    https://github.com/devsnd/tinytag
    https://github.com/authomatic/authomatic
    https://github.com/pennersr/django-allauth
    https://github.com/evonove/django-oauth-toolkit
    https://github.com/lepture/flask-oauthlib
    https://github.com/idan/oauthlib
    https://github.com/joestump/python-oauth2
    https://github.com/omab/python-social-auth
    https://github.com/litl/rauth
    https://github.com/demianbrecht/sanction
    https://github.com/demonware/jose
    https://github.com/jpadilla/pyjwt
    https://github.com/brianloveswords/python-jws
    https://github.com/davedoesdev/python-jwt
    http://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html
    http://www.buildout.org/en/latest/
    https://github.com/platformio/platformio-core
    https://github.com/pybuilder/pybuilder
    http://www.scons.org/
    https://github.com/python-attrs/attrs
    https://github.com/jab/bidict
    https://github.com/cdgriffith/Box
    https://github.com/carlosescri/DottedDict
    https://www.django-cms.org/en/
    http://djedi-cms.org/
    http://www.feincms.org/
    http://kotti.pylonsproject.org/
    http://mezzanine.jupo.org/
    http://opps.github.io/opps/
    https://plone.org/
    http://quokkaproject.org/
    https://wagtail.io/
    https://wid.gy/
    https://github.com/bbangert/beaker
    http://www.grantjenks.com/docs/diskcache/
    https://github.com/django-cache-machine/django-cache-machine
    https://github.com/Suor/django-cacheops
    https://github.com/5monkeys/django-viewlet
    http://dogpilecache.readthedocs.io/en/latest/
    https://pypi.python.org/pypi/HermesCache
    https://github.com/jmoiron/johnny-cache
    https://github.com/lericson/pylibmc
    http://libmemcached.org/libMemcached.html
    http://errbot.io/en/latest/
    https://pypi.python.org/pypi/pyspark/
    https://spark.apache.org/
    https://dask.pydata.org/en/latest/
    https://github.com/robinhood/faust
    https://kafka.apache.org/documentation/streams/
    https://github.com/spotify/luigi
    https://github.com/Yelp/mrjob
    https://github.com/Parsely/streamparse
    http://storm.apache.org/
    https://github.com/mre/awesome-static-analysis
    https://pypi.python.org/pypi/flake8
    http://coala.io/
    https://github.com/scottrogowski/code2flow
    https://github.com/landscapeio/prospector
    https://github.com/gak/pycallgraph
    https://github.com/klen/pylama
    https://www.pylint.org/
    http://mypy-lang.org/
    https://github.com/facebook/pyre-check
    https://github.com/Instagram/MonkeyType
    http://builtoncement.com/
    http://click.pocoo.org/dev/
    https://docs.openstack.org/developer/cliff/
    https://github.com/kennethreitz/clint
    http://docopt.org/
    https://github.com/chriskiehl/Gooey
    https://github.com/google/python-fire
    https://github.com/jonathanslenders/python-prompt-toolkit
    https://github.com/peterbrittain/asciimatics
    https://github.com/glamp/bashplotlib
    https://pypi.python.org/pypi/colorama
    https://github.com/aws/aws-cli
    https://github.com/audreyr/cookiecutter
    https://github.com/sloria/doitlive
    https://github.com/gleitz/howdoi
    https://github.com/jakubroztocil/httpie
    https://github.com/cloudnativelabs/kube-shell
    https://github.com/dbcli/mycli
    https://github.com/facebook/PathPicker
    https://github.com/mooz/percol
    https://github.com/dbcli/pgcli
    https://github.com/donnemartin/saws
    https://github.com/nvbn/thefuck
    https://github.com/tony/tmuxp
    https://github.com/tmux/tmux
    https://github.com/timofurrer/try
    http://python-future.org/index.html
    https://github.com/mitsuhiko/python-modernize
    https://pypi.python.org/pypi/six
    http://opencv.org/
    https://github.com/openpaperwork/pyocr
    https://github.com/madmaze/pytesseract
    https://github.com/tesseract-ocr
    http://simplecv.org/
    https://docs.python.org/3/library/multiprocessing.html
    https://docs.python.org/3/library/threading.html
    http://eventlet.net/
    http://www.gevent.org/
    https://github.com/python-greenlet/greenlet
    https://github.com/soravux/scoop
    https://github.com/madisonmay/Tomorrow
    https://github.com/MagicStack/uvloop
    https://www.red-dove.com/config-doc/
    https://docs.python.org/3/library/logging.html
    http://www.voidspace.org.uk/python/configobj.html
    https://docs.python.org/3/library/configparser.html
    http://profig.readthedocs.org/en/default/
    https://github.com/henriquebastos/python-decouple
    https://cryptography.io/en/latest/
    https://github.com/davidaurelio/hashids-python
    http://hashids.org
    http://www.paramiko.org/
    https://passlib.readthedocs.io/en/stable/
    https://github.com/pyca/pynacl
    https://github.com/blaze/blaze
    https://github.com/mining/mining
    https://orange.biolab.si/
    http://pandas.pydata.org/
    https://github.com/ironmussa/Optimus
    https://github.com/pyeve/cerberus
    https://docs.pylonsproject.org/projects/colander/en/latest/
    https://plot.ly/products/dash/
    https://github.com/Acrotrend/awesome-dash
    https://github.com/Julian/jsonschema
    http://json-schema.org/
    https://github.com/keleshev/schema
    https://github.com/schematics/schematics
    https://github.com/podio/valideer
    https://github.com/alecthomas/voluptuous
    https://github.com/sorrycc/awesome-javascript#data-visualization
    https://github.com/altair-viz/altair
    https://github.com/bokeh/bokeh
    https://github.com/bloomberg/bqplot
    https://github.com/yhat/ggpy
    http://matplotlib.org/
    http://www.pygal.org/en/latest/
    https://pypi.python.org/pypi/pygraphviz
    http://www.graphviz.org/
    http://www.pyqtgraph.org/
    https://github.com/mwaskom/seaborn
    https://github.com/vispy/vispy
    https://pythonhosted.org/pickleDB/
    https://github.com/msiemens/tinydb
    http://www.zodb.org/en/latest/
    http://shlomi-noach.github.io/awesome-mysql/
    https://github.com/PyMySQL/mysqlclient-python
    https://sourceforge.net/projects/mysql-python/
    https://pythonhosted.org/oursql/
    https://github.com/PyMySQL/PyMySQL
    https://github.com/dhamaniasad/awesome-postgres
    http://initd.org/psycopg/
    https://github.com/gmr/queries
    https://github.com/wulczer/txpostgres
    http://rogerbinns.github.io/apsw/
    https://github.com/pudo/dataset
    http://www.pymssql.org/en/latest/
    https://github.com/datastax/python-driver
    https://github.com/wbolster/happybase
    https://github.com/dpkp/kafka-python
    http://py2neo.org/2.0/
    https://docs.mongodb.com/ecosystem/drivers/python/
    https://github.com/andymccurdy/redis-py
    https://github.com/mongodb/motor
    https://github.com/driftx/Telephus
    https://github.com/deldotdr/txRedis
    https://github.com/KoffeinFlummi/Chronyk
    https://github.com/dateutil/dateutil
    https://docs.python.org/3/library/datetime.html
    https://github.com/myusuf3/delorean/
    https://github.com/zachwill/moment
    http://momentjs.com/
    https://github.com/sdispater/pendulum
    https://github.com/shinux/PyTime
    https://launchpad.net/pytz
    https://en.wikipedia.org/wiki/Tz_database
    https://github.com/dirn/When.py
    https://github.com/kennethreitz/maya
    https://pypi.python.org/pypi/ipdb
    https://docs.python.org/3/library/pdb.html
    https://pypi.python.org/pypi/pdbpp/
    https://pypi.python.org/pypi/pudb
    https://github.com/ionelmc/python-remote-pdb
    https://github.com/Kozea/wdb
    https://github.com/rkern/line_profiler
    https://github.com/fabianp/memory_profiler
    https://github.com/what-studio/profiling
    https://github.com/benfred/py-spy
    https://github.com/uber/pyflame
    https://github.com/nvdv/vprof
    https://github.com/gruns/icecream
    https://github.com/jazzband/django-debug-toolbar
    https://github.com/dcramer/django-devserver
    https://github.com/mgood/flask-debugtoolbar
    https://github.com/ionelmc/python-hunter
    https://github.com/khamidou/lptrace
    http://man7.org/linux/man-pages/man1/strace.1.html
    https://github.com/ionelmc/python-manhole
    https://github.com/eliben/pyelftools
    https://github.com/google/pyringe
    https://github.com/ChristosChristofidis/awesome-deep-learning
    https://github.com/BVLC/caffe
    https://github.com/fchollet/keras
    https://github.com/dmlc/mxnet
    http://neupy.com/pages/home.html
    http://pytorch.org/
    https://github.com/SerpentAI/SerpentAI
    https://github.com/tensorflow/tensorflow
    https://github.com/Theano/Theano
    https://github.com/ansible/ansible
    http://cloudinit.readthedocs.io/en/latest/
    https://github.com/sebastien/cuisine
    https://docs.docker.com/compose/
    https://www.docker.com/
    http://www.fabfile.org/
    https://github.com/fabtools/fabtools
    https://github.com/nickstenning/honcho
    https://github.com/ddollar/foreman
    https://www.openstack.org/
    https://github.com/pexpect/pexpect
    https://github.com/giampaolo/psutil
    https://github.com/saltstack/salt
    https://github.com/Supervisor/supervisor
    https://github.com/spotify/dh-virtualenv
    http://nuitka.net/
    http://pythonhosted.org/py2app/
    http://www.py2exe.org/
    https://github.com/pyinstaller/pyinstaller
    http://pynsist.readthedocs.io/en/latest/
    http://www.sphinx-doc.org/en/latest/
    https://github.com/yoloseem/awesome-sphinxdoc
    http://www.mkdocs.org/
    https://github.com/BurntSushi/pdoc
    https://github.com/pycco-docs/pycco
    https://github.com/s3tools/s3cmd
    https://github.com/bloomreach/s4cmd
    http://you-get.org/
    http://rg3.github.io/youtube-dl/
    https://github.com/lxneng/alipay
    https://github.com/stephenmcd/cartridge
    http://oscarcommerce.com/
    https://github.com/awesto/django-shop
    https://github.com/agiliq/merchant
    https://github.com/carlospalol/money
    https://github.com/Alir3z4/python-currencies
    https://github.com/MicroPyramid/forex-python
    http://getsaleor.com/
    https://www.shuup.com/en/
    https://github.com/jorgenschaefer/elpy
    https://github.com/DamnWidget/anaconda
    https://github.com/srusskih/SublimeJEDI
    https://github.com/davidhalter/jedi-vim
    https://github.com/python-mode/python-mode
    https://github.com/Valloric/YouCompleteMe
    https://github.com/davidhalter/jedi
    https://github.com/Microsoft/PTVS
    https://github.com/DonJayamanne/pythonVSCode
    https://github.com/MagicStack/MagicPython
    http://www.liclipse.com/
    https://www.jetbrains.com/pycharm/
    https://github.com/spyder-ide/spyder
    http://tomekwojcik.github.io/envelopes/
    https://github.com/mailgun/flanker
    https://github.com/martinrusev/imbox
    https://github.com/kennethreitz/inbox.py
    https://github.com/zedshaw/lamson
    https://github.com/marrow/mailer
    https://github.com/modoboa/modoboa
    https://github.com/nylas/sync-engine
    https://github.com/kootenpv/yagmail
    https://github.com/kennethreitz/pipenv
    https://github.com/qw3rtman/p
    https://github.com/pyenv/pyenv
    https://docs.python.org/3/library/venv.html
    https://pypi.python.org/pypi/virtualenv
    https://pypi.python.org/pypi/virtualenvwrapper
    https://docs.python.org/3/library/mimetypes.html
    https://github.com/jaraco/path.py
    https://docs.python.org/3/library/os.path.html
    https://docs.python.org/3/library/pathlib.html
    https://github.com/pyfilesystem/pyfilesystem2
    https://github.com/ahupp/python-magic
    https://github.com/mikeorr/Unipath
    https://github.com/gorakhargosh/watchdog
    https://pypi.python.org/pypi/cffi
    https://docs.python.org/3/library/ctypes.html
    https://mathema.tician.de/software/pycuda/
    http://www.swig.org/Doc1.3/Python.html
    https://github.com/Pylons/deform
    https://github.com/dyve/django-bootstrap3
    https://github.com/django-crispy-forms/django-crispy-forms
    https://github.com/WiserTogether/django-remote-forms
    https://github.com/wtforms/wtforms
    http://coconut-lang.org/
    https://github.com/pytoolz/cytoolz/
    https://github.com/kachayev/fn.py
    https://github.com/Suor/funcy
    https://github.com/pytoolz/toolz
    https://docs.python.org/3/library/curses.html
    http://www.gnu.org/software/ncurses/
    https://github.com/ChrisKnott/Eel
    https://github.com/nucleic/enaml
    https://github.com/zoofIO/flexx
    https://kivy.org/
    https://bitbucket.org/pyglet/pyglet/wiki/Home
    https://wiki.gnome.org/Projects/PyGObject
    https://riverbankcomputing.com/software/pyqt/intro
    https://www.qt.io/
    https://wiki.qt.io/PySide
    http://www.qt.io/
    https://github.com/r0x0r/pywebview/
    https://wiki.python.org/moin/TkInter
    https://github.com/pybee/toga
    http://urwid.org/
    https://wxpython.org/
    http://cocos2d.org/
    https://www.panda3d.org/
    http://www.pygame.org/news.html
    http://www.ogre3d.org/tikiwiki/PyOgre
    http://pyopengl.sourceforge.net/
    http://pysdl2.readthedocs.io/en/rel_0_9_5/
    https://www.renpy.org/
    https://github.com/SmileyChris/django-countries
    https://docs.djangoproject.com/en/dev/ref/contrib/gis/
    https://github.com/maxmind/geoip-api-python
    https://github.com/frewsxcv/python-geojson
    https://github.com/geopy/geopy
    https://github.com/appliedsec/pygeoip
    https://www.crummy.com/software/BeautifulSoup/bs4/doc/
    https://github.com/mozilla/bleach
    https://pypi.python.org/pypi/cssutils/
    https://github.com/html5lib/html5lib-python
    http://lxml.de/
    https://github.com/pallets/markupsafe
    https://github.com/gawel/pyquery
    https://github.com/stchris/untangle
    http://weasyprint.org
    https://xmldataset.readthedocs.io/en/latest/
    https://github.com/martinblech/xmltodict
    https://github.com/kennethreitz/grequests
    https://github.com/httplib2/httplib2
    http://docs.python-requests.org/en/latest/
    https://github.com/twisted/treq
    https://github.com/shazow/urllib3
    http://inotool.org/
    https://www.arduino.cc/
    https://github.com/boppreh/keyboard
    https://github.com/boppreh/mouse
    http://www.pingo.io/
    https://github.com/SavinaRoja/PyUserInput
    https://github.com/secdev/scapy
    https://github.com/rockymeza/wifi
    https://github.com/rossgoodwin/hmap
    https://sourceforge.net/projects/imgseek/
    https://github.com/hhatto/nude.py
    https://github.com/daboth/pagan
    https://github.com/python-pillow/Pillow
    http://www.pythonware.com/products/pil/
    https://pythonhosted.org/pyBarcode/
    https://github.com/ajkumar25/pygram
    https://github.com/lincolnloop/python-qrcode
    https://github.com/fogleman/Quads
    http://scikit-image.org/
    https://github.com/thumbor/thumbor
    https://github.com/dahlia/wand
    http://www.imagemagick.org/script/magick-wand.php
    https://github.com/metawilm/cl-python
    https://github.com/python/cpython
    http://cython.org/
    https://github.com/google/grumpy
    https://github.com/IronLanguages/ironpython3
    https://hg.python.org/jython
    https://github.com/micropython/micropython
    http://numba.pydata.org/
    https://github.com/Maratyszcza/PeachPy
    https://github.com/Microsoft/Pyjion
    https://bitbucket.org/pypy/pypy
    https://github.com/ebranca/owasp-pysec
    https://github.com/dropbox/pyston
    https://bitbucket.org/stackless-dev/stackless/wiki/Home
    https://github.com/bpython/bpython
    https://jupyter.org
    https://github.com/markusschanta/awesome-jupyter
    https://github.com/jonathanslenders/ptpython
    http://babel.pocoo.org/en/latest/
    https://github.com/ovalhub/pyicu
    http://site.icu-project.org/
    http://apscheduler.readthedocs.io/en/latest/
    https://github.com/thauber/django-schedule
    http://pydoit.org/
    https://github.com/gunnery/gunnery
    http://pythonhosted.org/joblib/index.html
    https://github.com/fengsp/plan
    https://github.com/dbader/schedule
    https://github.com/knipknap/SpiffWorkflow
    https://docs.openstack.org/developer/taskflow/
    https://github.com/ScatterHQ/eliot
    http://logbook.readthedocs.io/en/stable/
    https://github.com/getsentry/raven-python
    https://github.com/josephmisiti/awesome-machine-learning#python
    https://github.com/h2oai/h2o-3
    https://github.com/benhamner/Metrics
    https://github.com/numenta/nupic
    http://scikit-learn.org/
    http://spark.apache.org/docs/latest/ml-guide.html
    http://spark.apache.org/
    https://github.com/josephreisinger/vowpal_porpoise
    https://github.com/JohnLangford/vowpal_wabbit/
    https://github.com/dmlc/xgboost
    http://python-xy.github.io/
    http://www.lfd.uci.edu/~gohlke/pythonlibs/
    https://github.com/pythonnet/pythonnet
    https://sourceforge.net/projects/pywin32/
    https://winpython.github.io/
    https://github.com/jek/blinker
    https://github.com/pallets/itsdangerous
    https://github.com/mitsuhiko/pluginbase
    https://github.com/PacketPerception/pychievements
    http://www.tryton.org/
    https://github.com/RaRe-Technologies/gensim
    https://github.com/fxsjy/jieba
    https://github.com/saffsd/langid.py
    http://www.nltk.org/
    http://www.clips.ua.ac.be/pattern
    https://github.com/aboSamoor/polyglot
    https://github.com/isnowfy/snownlp
    https://spacy.io/
    https://github.com/sloria/TextBlob
    https://github.com/PetrochukM/PyTorch-NLP
    http://mininet.org/
    https://github.com/noxrepo/pox
    http://frenetic-lang.org/pyretic/
    https://github.com/sdn-ixp/internet2award
    https://docs.python.org/3/library/asyncio.html
    https://github.com/timofurrer/awesome-asyncio
    https://github.com/dieseldev/diesel
    https://github.com/quantmind/pulsar
    http://zeromq.github.io/pyzmq/
    https://twistedmatrix.com/trac/
    https://github.com/smira/txZMQ
    https://github.com/napalm-automation/napalm
    https://github.com/justquick/django-activity-stream
    https://github.com/tschellenbach/Stream-Framework
    https://docs.djangoproject.com/en/dev/topics/db/models/
    http://www.sqlalchemy.org/
    https://github.com/dahlia/awesome-sqlalchemy
    https://orator-orm.com
    https://github.com/coleifer/peewee
    https://ponyorm.com/
    https://github.com/web2py/pydal/
    https://pypi.python.org/pypi/python-sql
    https://github.com/django-nonrel/mongodb-engine
    https://github.com/stevearc/flywheel
    https://github.com/stephenmcd/hot-redis
    http://mongoengine.org/
    https://github.com/pynamodb/PynamoDB
    https://aws.amazon.com/dynamodb/
    https://github.com/kiddouk/redisco
    https://github.com/terrible-ideas/butterdb
    https://pip.pypa.io/en/stable/
    https://pypi.python.org/pypi
    https://github.com/conda/conda/
    http://clarete.li/curdling/
    https://github.com/jazzband/pip-tools
    http://pythonwheels.com/
    https://github.com/pypa/warehouse
    https://pypi.org/
    https://bitbucket.org/pypa/bandersnatch
    http://doc.devpi.net/latest/
    https://github.com/jazzband/localshop
    https://github.com/neuman/python-carteblanche/
    https://github.com/django-guardian/django-guardian
    https://github.com/dfunckt/django-rules
    https://github.com/kennethreitz/delegator.py
    https://docs.python.org/3.6/library/subprocess.html
    http://sarge.readthedocs.io/en/latest/
    https://github.com/amoffat/sh
    http://www.celeryproject.org/
    https://github.com/coleifer/huey
    https://github.com/pricingassistant/mrq
    http://python-rq.org/
    https://github.com/rdegges/simpleq
    https://github.com/spotify/annoy
    https://github.com/ibayer/fastFM
    https://github.com/benfred/implicit
    https://github.com/guestwalk/libffm
    https://github.com/lyst/lightfm
    https://github.com/maciejkula/spotlight
    http://surpriselib.com
    https://github.com/jfkirk/tensorrec
    http://www.django-rest-framework.org/
    http://tastypieapi.org/
    https://github.com/pyeve/eve
    https://github.com/marselester/flask-api-utils
    http://www.flaskapi.org/
    https://github.com/flask-restful/flask-restful
    https://github.com/jfinkels/flask-restless
    https://github.com/Cornices/cornice
    http://falconframework.org/
    https://github.com/timothycrosley/hug
    https://github.com/toastdriven/restless
    https://github.com/vertical-knowledge/ripozo
    https://github.com/jeffknupp/sandman
    https://github.com/encode/apistar
    https://github.com/joshmarshall/jsonrpclib/
    https://docs.python.org/3/library/xmlrpc.server.html
    https://github.com/0rpc/zerorpc-python
    http://zeromq.org/
    http://msgpack.org/
    http://www.astropy.org/
    https://github.com/chapmanb/bcbio-nextgen
    https://github.com/chapmanb/bcbb
    http://biopython.org/wiki/Main_Page
    http://cclib.github.io/
    http://colour-science.org/
    https://networkx.github.io/
    http://nipy.org
    http://www.numpy.org/
    http://openbabel.org/wiki/Main_Page
    https://github.com/obspy/obspy/wiki/
    http://www.pydy.org/
    https://github.com/pymc-devs/pymc3
    http://qutip.org/
    http://www.rdkit.org/
    https://www.scipy.org/
    https://github.com/statsmodels/statsmodels
    https://github.com/sympy/sympy
    https://github.com/quantopian/zipline
    https://bitbucket.org/simpy/simpy
    https://github.com/django-haystack/django-haystack
    https://github.com/elastic/elasticsearch-dsl-py
    https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html
    https://www.elastic.co/products/elasticsearch
    https://github.com/seek-ai/esengine
    https://github.com/django-haystack/pysolr
    https://github.com/edsu/solrpy
    http://lucene.apache.org/solr/
    http://whoosh.readthedocs.io/en/latest/
    https://github.com/marshmallow-code/marshmallow
    https://github.com/apex/apex
    https://aws.amazon.com/lambda/
    https://github.com/nficano/python-lambda
    https://github.com/Miserlou/Zappa
    https://github.com/kennethreitz/tablib
    https://github.com/brianray/mm
    https://openpyxl.readthedocs.io/en/default/
    https://github.com/pyexcel/pyexcel
    https://github.com/python-openxml/python-docx
    https://github.com/scanny/python-pptx
    http://relatorio.tryton.org/
    https://github.com/dagwieers/unoconv
    https://xlsxwriter.readthedocs.io
    https://www.xlwings.org
    https://github.com/python-excel/xlwt
    https://github.com/python-excel/xlrd
    https://github.com/euske/pdfminer
    https://github.com/mstamy2/PyPDF2
    http://www.reportlab.com/opensource/
    https://github.com/lepture/mistune
    https://github.com/waylan/Python-Markdown
    http://pyyaml.org/
    https://github.com/wireservice/csvkit
    https://github.com/mitsuhiko/unp
    https://github.com/eudicots/Cactus
    http://hyde.github.io/
    https://www.getlektor.com/
    https://www.getnikola.com/
    https://blog.getpelican.com/
    http://tinkerer.me/
    https://github.com/alex/django-taggit
    https://genshi.edgewall.org/
    https://github.com/pallets/jinja
    http://www.makotemplates.org/
    https://github.com/HypothesisWorks/hypothesis-python
    http://nestorsalceda.github.io/mamba/
    https://github.com/nose-devs/nose
    https://github.com/nose-devs/nose2
    https://docs.pytest.org/en/latest/
    https://github.com/robotframework/robotframework
    https://docs.python.org/3/library/unittest.html
    https://github.com/CleanCut/green
    https://tox.readthedocs.io/en/latest/
    https://github.com/locustio/locust
    https://github.com/asweigart/pyautogui
    https://pypi.python.org/pypi/selenium
    http://www.seleniumhq.org/
    https://github.com/seatgeek/sixpack
    https://github.com/cobrateam/splinter
    https://pypi.python.org/pypi/doublex
    https://github.com/spulec/freezegun
    https://github.com/patrys/httmock
    https://github.com/gabrielfalcao/HTTPretty
    https://docs.python.org/3/library/unittest.mock.html
    https://github.com/mindflayer/python-mocket
    https://github.com/getsentry/responses
    https://github.com/kevin1024/vcrpy
    https://github.com/FactoryBoy/factory_boy
    https://github.com/klen/mixer
    https://github.com/vandersonmota/model_mommy
    https://pypi.python.org/pypi/coverage
    https://github.com/lk-geimfari/mimesis
    https://github.com/emirozer/fake2db
    https://github.com/joke2k/faker
    https://pypi.python.org/pypi/radar
    https://github.com/ajalt/fuckitpy
    https://github.com/chardet/chardet
    https://docs.python.org/3/library/difflib.html
    https://github.com/LuminosoInsight/python-ftfy
    https://github.com/seatgeek/fuzzywuzzy
    https://github.com/ztane/python-Levenshtein/
    https://github.com/vinta/pangu.py
    https://github.com/pwaller/pyfiglet
    https://github.com/mozillazg/python-pinyin
    https://github.com/skorokithakis/shortuuid
    https://github.com/orsinium/textdistance
    https://pypi.python.org/pypi/Unidecode
    https://github.com/moskytw/uniout
    https://github.com/lxneng/xpinyin
    https://github.com/dimka665/awesome-slugify
    https://github.com/un33k/python-slugify
    https://github.com/mozilla/unicode-slugify
    https://github.com/daviddrysdale/python-phonenumbers
    http://www.dabeaz.com/ply/
    http://pygments.org/
    http://pyparsing.wikispaces.com/
    https://github.com/derek73/python-nameparser
    https://github.com/selwin/python-user-agents
    https://github.com/andialbrecht/sqlparse
    https://github.com/realpython/list-of-python-api-wrappers
    https://libcloud.apache.org/
    https://github.com/boto/boto3
    https://github.com/istrategylabs/django-wordpress
    https://github.com/mobolic/facebook-sdk
    https://github.com/jgorset/facepy
    https://github.com/charlierguo/gmail
    https://github.com/google/google-api-python-client
    https://github.com/burnash/gspread
    https://github.com/ryanmcgrath/twython
    https://github.com/gruns/furl
    https://github.com/codeinthehole/purl
    https://github.com/ellisonleao/pyshorteners
    https://github.com/Alir3z4/python-short_url
    https://github.com/sloria/webargs
    http://zulko.github.io/moviepy/
    https://github.com/aizvorski/scikit-video
    https://pypi.python.org/pypi/bjoern
    http://www.fapws.org/
    https://pypi.python.org/pypi/gunicorn
    https://pypi.python.org/pypi/meinheld
    https://github.com/hivesolutions/netius
    https://pypi.python.org/pypi/rocket
    https://uwsgi-docs.readthedocs.io/en/latest/
    https://waitress.readthedocs.io/en/latest/
    http://werkzeug.pocoo.org/
    https://github.com/vinta/Haul
    https://github.com/Alir3z4/html2text
    https://github.com/michaelhelmick/lassie
    https://github.com/coleifer/micawber
    https://github.com/codelucas/newspaper
    https://github.com/grangier/python-goose
    https://github.com/buriy/python-readability
    https://github.com/kennethreitz/requests-html
    https://github.com/Alir3z4/python-sanitize
    https://github.com/miso-belica/sumy
    https://github.com/deanmalmgren/textract
    https://github.com/gaojiuli/toapi
    https://github.com/chineking/cola
    https://github.com/matiasb/demiurge
    http://pythonhosted.org/feedparser/
    http://grablib.org/
    https://github.com/hickford/MechanicalSoup
    https://github.com/scrapinghub/portia
    https://github.com/binux/pyspider
    https://github.com/jmcarp/robobrowser
    https://scrapy.org/
    https://www.djangoproject.com/
    https://github.com/rosarior/awesome-django
    http://flask.pocoo.org/
    https://github.com/humiaozuzu/awesome-flask
    https://pylonsproject.org/
    https://github.com/uralbash/awesome-pyramid
    https://github.com/channelcat/sanic
    http://www.tornadoweb.org/en/latest/
    https://vibora.io/
    https://github.com/crossbario/autobahn-python
    https://github.com/crossbario/crossbar/
    https://github.com/django/channels
    https://github.com/stephenmcd/django-socketio
    https://github.com/Lawouach/WebSocket-for-Python
    https://github.com/ciandcd/awesome-ciandcd#online-build-system
    https://circleci.com/
    https://travis-ci.org
    https://travis-ci.com
    https://vexor.io
    http://www.wercker.com/
    https://www.codacy.com/
    https://codecov.io/
    https://www.codefactor.io/
    https://landscape.io/
    http://frompythonimportpodcast.com/
    https://podcastinit.com/
    https://pythonbytes.fm
    http://pythontesting.net
    http://radiofreepython.com/
    https://talkpython.fm/
    https://twitter.com/codetengu
    https://twitter.com/getpy
    https://twitter.com/importpython
    https://twitter.com/planetpython
    https://twitter.com/pycoders
    https://twitter.com/pypi
    https://twitter.com/pythontrending
    https://twitter.com/PythonWeekly
    https://twitter.com/talkpython
    https://twitter.com/realpython
    https://www.reddit.com/r/coolgithubprojects/
    https://www.reddit.com/r/python
    https://python.libhunt.com/
    https://djangopackages.org/
    https://www.fullstackpython.com/
    http://pypi-ranking.info/alltime
    http://python3wos.appspot.com/
    http://www.oss.io/open-source/
    https://python.zeef.com/alan.richmond
    https://www.ctolib.com/python/
    https://realpython.com
    https://github.com/trending?l=python
    https://weekly.codetengu.com/
    http://importpython.com/newsletter/
    http://pycoders.com/
    http://www.pythonweekly.com/
    https://realpython.com/python-tricks/
    https://github.com/lk-geimfari/awesomo
    https://github.com/jnv/lists
    https://github.com/kirang89/pycrumbs
    https://github.com/checkcheckzz/python-github-projects
    https://github.com/rasbt/python_reference
    https://github.com/svaksha/pythonidae
    https://www.cybrhome.com/topic/python-podcasts
    https://github.com/metakermit/awesome-python-for-social-good
    https://github.com/vinta/awesome-python/blob/master/CONTRIBUTING.md
    https://github.com/vinta/awesome-python/pulls
    https://twitter.com/vinta
    https://github.com/docker-library/python
    https://docs.docker.com/docker-hub/official_repos/
    https://hub.docker.com/_/python/
    https://github.com/docker-library/docs
    https://github.com/docker-library/docs/tree/master/python
    https://github.com/docker-library/official-images/blob/master/library/python
    https://github.com/docker-library/official-images/labels/library%2Fpython
    https://github.com/docker-library/official-images/blob/master/README.md
    https://travis-ci.org/docker-library/python/branches
    https://ci.appveyor.com/project/docker-library/python
    https://doi-janky.infosiftr.net/job/update.sh/job/python
    https://travis-ci.org/exercism/python
    https://pyup.io/repos/github/exercism/python/
    https://gitter.im/exercism/python?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
    https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md
    https://github.com/exercism/python/issues/417#issuecomment-366040062
    https://github.com/exercism/python/issues/272
    https://github.com/exercism/python/issues/440
    https://github.com/exercism/python/issues/477
    https://github.com/exercism/python/pull/419
    https://github.com/exercism/python/issues/784
    https://www.python.org/dev/peps/pep-0008/
    http://pep8.org
    http://flake8.readthedocs.org/en/latest/
    https://github.com/exercism/python/blob/master/.travis.yml
    https://chris.beams.io/posts/git-commit/#seven-rules
    http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
    https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md#git-basics
    /LICENSE
    http://solos.github.io/baidupan/
    http://pypi.python.org/pypi/chardet
    http://www.postgresql.org/
    https://www.postgresql.org/download/linux/ubuntu/
    https://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/
    https://docs.mongodb.org/v2.6/tutorial/install-mongodb-on-ubuntu/
    http://api.mongodb.org/python/current/installation.html
    http://api.mongodb.org/python/current/tutorial.html
    https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
    http://localhost:9200/_plugin/head/
    http://localhost:9200/_plugin/marvel/
    http://192.168.2.188:9200/_plugin/marvel/sense/index.html
    http://www.elasticsearch.cn/guide/
    http://es.xiaoleilu.com/
    http://elasticsearch-py.readthedocs.org/en/latest/
    http://pyes.readthedocs.org/en/latest/index.html
    http://kibana.logstash.es/
    https://pypi.python.org/pypi/redis
    http://doc.redisfans.com/
    http://pycoders-weekly-chinese.readthedocs.org/en/latest/issue6/processing-xml-in-python-with-element-tree.html
    https://docs.python.org/2/library/xml.etree.elementtree.html
    http://www.crummy.com/software/BeautifulSoup/download/4.x/
    http://www.crummy.com/software/BeautifulSoup/bs4/doc.zh/
    https://developers.google.com/image-search/v1/jsondevguide?csw=1
    http://docs.jinkan.org/docs/flask/
    http://docs.jinkan.org/docs/flask-wtf/
    http://www.pythondoc.com/flask-sqlalchemy/
    http://docs.jinkan.org/docs/flask-login/
    https://nodejs.org
    https://github.com/showcases/web-application-frameworks?s=stars
    https://readthedocs.org/
    https://farm1.staticflickr.com/628/33173824932_58add34581_k_d.jpg
    creational/abstract_factory.py
    creational/borg.py
    creational/builder.py
    creational/factory_method.py
    creational/lazy_evaluation.py
    creational/pool.py
    creational/prototype.py
    structural/3-tier.py
    structural/adapter.py
    structural/bridge.py
    structural/composite.py
    structural/decorator.py
    structural/facade.py
    structural/flyweight.py
    structural/front_controller.py
    structural/mvc.py
    structural/proxy.py
    behavioral/chain.py
    behavioral/catalog.py
    behavioral/chaining_method.py
    behavioral/command.py
    behavioral/iterator.py
    behavioral/mediator.py
    behavioral/memento.py
    behavioral/observer.py
    behavioral/publish_subscribe.py
    behavioral/registry.py
    behavioral/specification.py
    behavioral/state.py
    behavioral/strategy.py
    behavioral/template.py
    behavioral/visitor.py
    dft/setter_injection.py
    fundamental/delegation_pattern.py
    other/blackboard.py
    other/graph_search.py
    other/hsm/hsm.py
    https://travis-ci.org/AtsushiSakai/PythonRobotics
    https://pythonrobotics.readthedocs.io/en/latest/?badge=latest
    https://saythanks.io/to/AtsushiSakai
    #what-is-this
    #requirements
    #how-to-use
    #localization
    #extended-kalman-filter-localization
    #particle-filter-localization
    #histogram-filter-localization
    #mapping
    #gaussian-grid-map
    #ray-casting-grid-map
    #k-means-object-clustering
    #slam
    #iterative-closest-point-icp-matching
    #fastslam-10
    #graph-based-slam
    #path-planning
    #dynamic-window-approach
    #grid-based-search
    #dijkstra-algorithm
    #a-algorithm
    #potential-field-algorithm
    #state-lattice-planning
    #biased-polar-sampling
    #lane-sampling
    #probabilistic-road-map-prm-planning
    #rapidly-exploring-random-trees-rrt
    #rrt
    #rrt-with-reeds-sheep-path
    #lqr-rrt
    #quintic-polynomials-planning
    #reeds-shepp-planning
    #lqr-based-path-planning
    #optimal-trajectory-in-a-frenet-frame
    #path-tracking
    #move-to-a-pose-control
    #stanley-control
    #rear-wheel-feedback-control
    #linearquadratic-regulator-lqr-speed-and-steering-control
    #model-predictive-speed-and-steering-control
    #arm-navigation
    #n-joint-arm-to-point-control
    #arm-navigation-with-obstacle-avoidance
    #aerial-navigation
    #drone-3d-trajectory-following
    #license
    #contribution
    #support
    #authors
    https://arxiv.org/abs/1808.10703
    https://github.com/AtsushiSakai/PythonRoboticsPaper/blob/master/python_robotics.bib
    http://www.cvxpy.org/en/latest/
    https://pythonrobotics.readthedocs.io/
    http://www.probabilistic-robotics.org/
    https://cs.gmu.edu/~kosecka/cs685/cs685-icp.pdf
    http://www-personal.acfr.usyd.edu.au/tbailey/software/slam_simulations.htm
    http://www2.informatik.uni-freiburg.de/~stachnis/pdf/grisetti10titsmag.pdf
    https://www.ri.cmu.edu/pub_files/pub1/fox_dieter_1997_1/fox_dieter_1997_1.pdf
    https://www.cs.cmu.edu/~motionplanning/lecture/Chap4-Potential-Field_howie.pdf
    http://journals.sagepub.com/doi/pdf/10.1177/0278364906075328
    http://www.frc.ri.cmu.edu/~alonzo/pubs/papers/JFR_08_SS_Sampling.pdf
    https://en.wikipedia.org/wiki/Probabilistic_roadmap
    https://arxiv.org/abs/1005.0416
    http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.419.5503&rep=rep1&type=pdf
    http://lis.csail.mit.edu/pubs/perez-icra12.pdf
    https://github.com/MahanFathi/LQR-RRTstar
    http://ieeexplore.ieee.org/document/637936/
    http://planning.cs.uiuc.edu/node822.html
    https://pdfs.semanticscholar.org/932e/c495b1d0018fd59dee12a0bf74434fac7af4.pdf
    https://github.com/ghliu/pyReedsShepp
    https://www.researchgate.net/profile/Moritz_Werling/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame/links/54f749df0cf210398e9277af.pdf
    https://www.youtube.com/watch?v=Cj6tAQe7UCY
    https://link.springer.com/book/10.1007/978-3-642-20144-8
    http://robots.stanford.edu/papers/thrun.stanley05.pdf
    https://www.ri.cmu.edu/pub_files/2009/2/Automatic_Steering_Methods_for_Autonomous_Automobile_Path_Tracking.pdf
    https://arxiv.org/abs/1604.07446
    http://ieeexplore.ieee.org/document/5940562/
    https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathTracking/model_predictive_speed_and_steer_control/notebook.ipynb
    https://www.patreon.com/myenigma
    https://www.paypal.me/myenigmapay/
    https://github.com/AtsushiSakai/PythonRobotics/blob/master/users_comments.md
    https://github.com/AtsushiSakai/
    https://twitter.com/Atsushi_twi
    https://github.com/daniel-s-ingram
    https://github.com/jwdinius
    https://github.com/karanchawla
    https://github.com/araffin
    https://github.com/AlexisTM
    https://github.com/scotty3785/python

]
